version: '3'

volumes:
  pgdata: {}
  pgadmindata: {}

services:

  postgres:
    build:
      context: ./.docker/postgres/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data:/tmp/data
      - pgdata:/var/lib/postgresql/data:Z
      - .docker/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    env_file:
      - ./.env/.postgres
    environment:
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    build:
      context: ./.docker/pgadmin/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    volumes:
      - pgadmindata:/var/lib/pgadmin
    env_file:
      - ./.env/.pgadmin
    environment:
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    networks:
      - app-network

  notebook:
    build:
      context: ./.docker/notebook/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data:/home/jovyan/data
      - ./work:/home/jovyan/work
    depends_on:
      - postgres
    ports:
      - "8888:8888"
    networks:
      - app-network

  python:
    build:
      context: ./.docker/python/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
