version: '3'

volumes:
  pgdata: {}
  pgadmindata: {}

services:

  postgres:
    build:
      context: ./.docker/postgres/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data:/tmp/data
      - pgdata:/var/lib/postgresql/data:Z
      - .docker/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - ./.env/.postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  pgadmin:
    build:
      context: ./.docker/pgadmin/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    volumes:
      - pgadmindata:/var/lib/pgadmin
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=pgadmin@tecnico.pt
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    env_file:
      - ./.env/.pgadmin
    ports:
      - "5050:5050"
    networks:
      - app-network

  python:
    build:
      context: ./.docker/python/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
