version: '3'

volumes:
  pgdata: {}
  pgadmindata: {}

services:

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - ./data:/tmp/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4:6.21
    restart: always
    depends_on:
      - postgres
    volumes:
      - pgadmindata:/var/lib/pgadmin
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=pgadmin@tecnico.pt
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    env_file:
      - ./.envs/.pgadmin
    ports:
      - "5050:5050"
    networks:
      - app-network

  python:
    build:
      context: .
      dockerfile: ./compose/python/Dockerfile
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
